apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  namespace: loadtest
spec:
  serviceName: worker-headless
  replicas: REPLICAS
  selector:
    matchLabels:
      app: nt-demo
  template:
    metadata:
      labels:
        app: nt-demo
        role: worker
    spec:
      serviceAccountName: nt-demo
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: nt-demo
          image: ghcr.io/rLukoyanov/nt-demo:latest
          imagePullPolicy: Always
          args: ["-election"]
          ports:
            - containerPort: 8080
              name: ui
            - containerPort: 8081
              name: worker
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LEASE_NAME
              value: nt-demo-leader
            - name: WORKERS_SVC
              value: worker-headless
            - name: WORKERS_COUNT
              value: "WORKERS_COUNT_VALUE"
            - name: WORKERS_PORT
              value: "8081"
            - name: WORKERS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 64Mi
            limits:
              cpu: "2"
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]