apiVersion: v1
kind: Service
metadata:
  name: worker-headless
  namespace: loadtest
spec:
  clusterIP: None
  selector:
    app: nt-demo-worker
  ports:
    - name: http
      port: 8081
      targetPort: 8081